version: '3'

services:
  mssql:
    build:
      context: ./docker/
    image: saphanaexpress
    container_name: saphanaexpress
    ports:
      - 39013:39013
      - 39017:39017
      - 39041-39045:39041-39045
      - 1128-1129:1128-1129
      - 59013-59014:59013-59014 
    environment:
      - DUMP_FOLDER=data
      - SOURCE_SCHEMA=SOURCE
      - SCHEMA_NAME=LOCALDEV
      - SCHEMA_PWD=P@ssw0rd!
    volumes:
      - ./db/data:/hana/mounts
    command:
      - --agree-to-sap-license
      - --dont-check-system
      - --dont-check-mount-points
      - --master-password
      - P@ssw0rd!