version: '3.1'

services:

  db:
    build:
      context: ./docker/
    image: postgres
    container_name: postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: P@ssw0rd!
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    restart: always
    user: root
    volumes:
      - ./docker/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/db/data:/var/lib/postgresql/data
      
      